-- 3단계 학습 DB의 구조와 권한만 재현합니다. 메모 본문과 실제 키는 포함하지 않습니다.
-- 새 학습용 프로젝트의 SQL Editor에서 실행합니다. 기존 가상 메모는 보존합니다.
begin;

create table if not exists public.notes (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid,
  position integer generated by default as identity not null unique check (position > 0),
  title text not null,
  content text not null,
  created_at timestamptz not null default now()
);

-- 기존 2단계 테이블에도 자동 순번을 추가합니다. 메모 본문과 소유자는 변경하지 않습니다.
do $$
begin
  if not exists (select 1 from pg_attribute where attrelid='public.notes'::regclass
      and attname='position' and attidentity <> '') then
    alter table public.notes alter column position add generated by default as identity;
  end if;
end $$;
select setval(pg_get_serial_sequence('public.notes','position'),
  greatest(coalesce(max(position),0)+1,1),false) from public.notes;

-- 심판 계정도 허용하므로 auth.users 외래키는 걸지 않습니다.
alter table public.notes enable row level security;
revoke all privileges on table public.notes from public, anon, authenticated;
grant usage on schema public to service_role;
grant select, insert, update, delete on table public.notes to service_role;
revoke all privileges on sequence public.notes_position_seq from public, anon, authenticated;
grant usage, select on sequence public.notes_position_seq to service_role;
create index if not exists notes_owner_position_idx on public.notes(owner_id, position);

-- 자동 RLS 기능을 켠 프로젝트에서 공개 RPC 실행만 제한합니다.
do $$
begin
  if to_regprocedure('public.rls_auto_enable()') is not null then
    revoke execute on function public.rls_auto_enable() from public, anon, authenticated;
  end if;
end $$;

commit;
